### ISSUE TITLE
Ensure the builds are reproducible

### ISSUE THREAD

**Issue by Minoru** [Minoru/git-submerge#20]
[Reproducible builds](https://reproducible-builds.org/) are all the rage these days, and for a good reason. 

- [ ] Check if current builds are reproducible
- [ ] Make them reproducible
- [ ] Add checks to Travis and Appveyor to ensure reproducibility isn't broken
